Repository blue-stream/blue-stream-client, pull requests merged in 2019-03, with the labels that each got.

#24 refactor: Hide subscribe button form channel and video-section-item
  package-lock.json
  src/app/channels/channel-header/channel-header.component.html
  src/app/video/video-section-list/video-section-item/video-section-item.component.html
Labels: enhancement

#26 feat: Add link to channel and "uploaded by" to watch page info
  src/app/app-routing.module.ts
  src/app/channels/channel/channel.component.ts
  src/app/channels/channels-routing.module.ts
  src/app/watch/watch-owner/watch-owner.component.html
  src/app/watch/watch-owner/watch-owner.component.scss
  src/app/watch/watch-owner/watch-owner.component.ts
  src/app/watch/watch-secondary-info/watch-secondary-info.component.html
  src/assets/i18n/en.json
  src/assets/i18n/he.json
Labels: enhancement

#27 Add avatar link
  src/app/comments/comment/comment.component.html
  src/app/shared/avatar/avatar.component.html
  src/app/shared/avatar/avatar.component.ts
  src/app/watch/watch-owner/watch-owner.component.html
Labels: enhancement

#30 feat: Hide watch-page video actions from unpermitted user
  src/app/shared/models/video.model.ts
  src/app/watch/watch-primary-info/watch-primary-info.component.html
  src/app/watch/watch-primary-info/watch-primary-info.component.ts
Labels: enhancement

#31 feat: Disable editing of profile channels
  src/app/channels/channel/channel.component.html
Labels: enhancement

#33 fix: Fix user's channel route
  src/app/channels/channels-routing.module.ts
Labels: bug

#36 feat: Add title to channel selection page on upload
  src/app/channels/channel-add/channel-add.component.html
  src/app/channels/channels.component.html
  src/app/channels/channels.component.scss
  src/assets/i18n/en.json
  src/assets/i18n/he.json
Labels: enhancement

#38 fix: fix watch page grid layout
  src/app/watch/watch.component.scss
Labels: bug

#35 fix: Fix bug when user enters profile from another channel and data d…
  src/app/channels/channel-about/channel-about.component.ts
  src/app/channels/channel-add/channel-add.component.ts
  src/app/channels/channel-form/channel-form.component.ts
  src/app/channels/channel-grid-item/channel-grid-item.component.ts
  src/app/channels/channel-grid/channel-grid.component.ts
  src/app/channels/channel-home/channel-home.component.ts
  src/app/channels/channel-manage/channel-manage.component.ts
  src/app/channels/channel-permission/channel-permission.component.ts
  src/app/channels/channel-permissions-form/channel-permissions-form.component.ts
  src/app/channels/channel-permissions/channel-permissions.component.ts
  src/app/channels/channel-search/channel-search.component.html
  src/app/channels/channel-search/channel-search.component.scss
  src/app/channels/channel-search/channel-search.component.ts
  src/app/channels/channel-videos/channel-videos.component.ts
  src/app/channels/channels-routing.module.ts
  src/app/channels/channels.component.ts
  src/app/channels/channels.module.ts
Labels: bug

#39 feat: Add video link after video publish on upload page
  src/app/upload/video-upload-progress/video-upload-progress.component.html
  src/app/upload/video-upload-progress/video-upload-progress.component.scss
  src/app/upload/video-upload-progress/video-upload-progress.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/he.json
Labels: enhancement

#44 feat: Add message for browsers that do not support css display: grid
  src/app/app.component.html
  src/app/app.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/he.json
Labels: enhancement

#47 fix: fix channel form
  src/app/channels/channel-form/channel-form.component.ts
Labels: bug

#48 refactor: remove mepty tab from channel page
  src/app/channels/channel-home/channel-home.component.html
  src/app/channels/channel-home/channel-home.component.scss
  src/app/channels/channel-home/channel-home.component.ts
  src/app/channels/channel/channel.component.html
  src/app/channels/channels.module.ts
Labels: enhancement

#50 feat: only display comment remove for comment's owners
  src/app/comments/comment-action-buttons/comment-action-buttons.component.html
  src/app/comments/comment-action-buttons/comment-action-buttons.component.ts
  src/app/comments/models/comment.model.ts
Labels: enhancement

#52 feat: Add popular and newest videos to dashboard
  src/app/core/services/video.service.ts
  src/app/video/video-section-list/video-section-item/video-section-item.component.html
  src/app/video/video-section-list/video-section-list.component.html
  src/app/video/video-section-list/video-section-list.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/he.json
Labels: enhancement

#53 Loading indicator
  src/app/channels/channel-videos/channel-videos.component.html
  src/app/channels/channel-videos/channel-videos.component.scss
  src/app/channels/channel-videos/channel-videos.component.ts
  src/app/channels/channels.component.html
  src/app/channels/channels.component.scss
  src/app/channels/channels.component.ts
  src/app/comments/comment/comment.component.html
  src/app/comments/comment/comment.component.scss
  src/app/comments/comment/comment.component.ts
  src/app/comments/comments.component.html
  src/app/comments/comments.component.scss
  src/app/comments/comments.component.ts
  src/app/popular/popular.component.html
  src/app/popular/popular.component.scss
  src/app/popular/popular.component.ts
  src/app/search-results/search-results.component.html
  src/app/search-results/search-results.component.scss
  src/app/search-results/search-results.component.ts
  src/app/shared/models/video-section.model.ts
  src/app/shared/shared.module.ts
  src/app/video/video-section-list/video-section-item/video-section-item.component.html
  src/app/video/video-section-list/video-section-item/video-section-item.component.scss
  src/app/video/video-section-list/video-section-list.component.ts
  src/app/watch/watch.component.html
  src/app/watch/watch.component.scss
  src/app/watch/watch.component.ts
Labels: enhancement

#45 Classification
  package-lock.json
  src/app/app-routing.module.ts
  src/app/core/services/channel.service.ts
  src/app/core/services/video.service.ts
  src/app/shared/channel-tile/channel-tile.component.html
  src/app/shared/channel-tile/channel-tile.component.ts
  src/app/shared/models/classification.model.ts
  src/app/shared/models/video.model.ts
  src/app/shared/search/search.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/video-form/CrossFieldErrorMatcher.ts
  src/app/shared/video-form/video-form.component.html
  src/app/shared/video-form/video-form.component.scss
  src/app/shared/video-form/video-form.component.ts
  src/app/shared/video-tile/video-tile.component.ts
  src/app/upload/file-uploader.service.ts
  src/app/upload/video-upload-form/video-upload-form.component.html
  src/app/upload/video-upload-form/video-upload-form.component.scss
  src/app/upload/video-upload-form/video-upload-form.component.ts
  src/app/upload/video-upload.interface.ts
  src/app/upload/video-uploader/video-uploader.component.html
  src/app/upload/video-uploader/video-uploader.component.ts
  src/app/video-edit/video-edit-header/video-edit-header.component.html
  src/app/video-edit/video-edit-header/video-edit-header.component.scss
  src/app/video-edit/video-edit-header/video-edit-header.component.ts
  src/app/video-edit/video-edit-routing.module.ts
  src/app/video-edit/video-edit.component.html
  src/app/video-edit/video-edit.component.scss
  src/app/video-edit/video-edit.component.ts
  src/app/video-edit/video-edit.module.ts
  src/app/video/video-edit/video-edit.component.html
  src/app/video/video-edit/video-edit.component.scss
  src/app/video/video-edit/video-edit.component.ts
  src/app/video/video-routing.module.ts
  src/app/video/video.module.ts
  src/app/watch/watch-description/watch-description.component.html
  src/app/watch/watch-description/watch-description.component.scss
  src/app/watch/watch-description/watch-description.component.ts
  src/app/watch/watch-primary-info/watch-primary-info.component.html
  src/app/watch/watch-primary-info/watch-primary-info.component.scss
  src/app/watch/watch-secondary-info/watch-secondary-info.component.html
  src/assets/i18n/en.json
  src/assets/i18n/he.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#57 fix: fix video-section-list loading
  src/app/video/video-section-list/video-section-list.component.ts
Labels: bug

#62 Refactor video form
  src/app/core/services/classification.service.ts
  src/app/core/services/video.service.ts
  src/app/shared/models/classification.model.ts
  src/app/shared/models/video.model.ts
  src/app/shared/video-form/video-form.component.html
  src/app/shared/video-form/video-form.component.ts
  src/app/watch/watch-description/watch-description.component.html
  src/app/watch/watch-description/watch-description.component.ts
  src/app/watch/watch.component.ts
Labels: enhancement

#60 Fix loading
  src/app/channels/channel-videos/channel-videos.component.scss
  src/app/channels/channel-videos/channel-videos.component.ts
  src/app/channels/channels.component.scss
  src/app/channels/channels.component.ts
  src/app/comments/comment/comment.component.scss
  src/app/comments/comment/comment.component.ts
  src/app/comments/comments.component.scss
  src/app/comments/comments.component.ts
  src/app/popular/popular.component.scss
  src/app/popular/popular.component.ts
  src/app/search-results/search-results.component.scss
  src/app/search-results/search-results.component.ts
  src/app/video/video-section-list/video-section-item/video-section-item.component.scss
  src/app/video/video-section-list/video-section-list.component.html
  src/app/video/video-section-list/video-section-list.component.scss
  src/app/video/video-section-list/video-section-list.component.ts
  src/app/watch/watch.component.scss
  src/app/watch/watch.component.ts
Labels: bug

#61 fix: fix channel avatar not displaying
  src/app/shared/avatar/avatar.component.ts
Labels: bug

#63 refactor: display more videos in popular videos page
  src/app/popular/popular.component.ts
Labels: enhancement

#64 Fix comment word break
  src/app/comments/comment-form/comment-form.component.html
  src/app/comments/comment/comment.component.scss
Labels: bug, enhancement

#65 fix: fix build --prod bugs
  src/app/channels/channel-form/channel-form.component.html
  src/app/channels/channel-form/channel-form.component.ts
  src/app/channels/channel-permissions-form/channel-permissions-form.component.html
  src/app/channels/channel-permissions-form/channel-permissions-form.component.ts
  src/app/comments/comment-form/comment-form.component.ts
  src/app/comments/comment/comment.component.html
  src/app/comments/comment/comment.component.ts
  src/app/comments/models/comment.model.ts
  src/app/shared/channel-tile/channel-tile.component.ts
  src/app/shared/models/channel.model.ts
  src/app/shared/video-form/video-form.component.html
  src/app/shared/video-form/video-form.component.ts
  src/app/shared/video-player/video-player.component.html
  src/app/shared/video-tile/video-tile.component.html
  src/app/shared/video-tile/video-tile.component.ts
Labels: bug

#66 refactor: add isProfile to getMany channels
  src/app/core/services/channel.service.ts
Labels: bug
